<?php

return [
    'trial_days' => (int) env('RADAR_TRIAL_DAYS', 7),
    'digest_limit' => (int) env('RADAR_DIGEST_LIMIT', 8),
    'reminder_lead_minutes' => (int) env('RADAR_REMINDER_LEAD_MINUTES', 60),
    'max_preferences' => (int) env('RADAR_MAX_PREFERENCES', 12),
    'lots_url' => env('RADAR_LOTS_URL', 'https://acmachado14.github.io/leilao-radar/data/lotes.json'),
    'lots_path' => env('RADAR_LOTS_PATH'),
    'whatsapp' => [
        'enabled' => (bool) env('RADAR_WHATSAPP_ENABLED', false),
        'token' => env('WHATSAPP_TOKEN'),
        'phone_number_id' => env('WHATSAPP_PHONE_NUMBER_ID'),
        'template' => env('WHATSAPP_TEMPLATE', 'radar_lote_alert'),
    ],
    'gemini' => [
        'api_key' => env('RADAR_GEMINI_API_KEY'),
        'model' => env('RADAR_GEMINI_MODEL', 'gemini-3.6-flash'),
        'max_images' => (int) env('RADAR_GEMINI_MAX_IMAGES', 0),
        'target_profit_margin_pct' => (float) env('RADAR_GEMINI_TARGET_PROFIT_MARGIN_PCT', 15),
        'estimated_cost_brl' => (float) env('RADAR_GEMINI_ESTIMATED_COST_BRL', 0.18),
    ],
    'sales' => [
        'whatsapp' => env('RADAR_SALES_WHATSAPP', '5531986268630'),
    ],
    'plans' => [
        'trial' => [
            'name' => 'Trial',
            'tagline' => 'Teste a IA em 3 carros e veja o teto de lance.',
            'price' => 'Grátis por 7 dias',
            'price_note' => 'Depois fale com o atendente para continuar.',
            'analyses_per_month' => 3,
            'alerts' => 2,
            'highlight' => false,
            'cta' => 'Começar grátis',
            'features' => [
                '3 análises de IA por mês',
                'Teto de lance com base na FIPE',
                '2 recortes de alerta por e-mail',
                'Digest diário das ofertas da sua faixa',
            ],
        ],
        'radar' => [
            'name' => 'Radar',
            'tagline' => 'Alertas no ponto + IA para não pagar caro no pátio.',
            'price' => 'R$ 49/mês',
            'price_note' => 'Ativação manual após o WhatsApp.',
            'analyses_per_month' => 20,
            'alerts' => 6,
            'highlight' => false,
            'cta' => 'Falar com atendente',
            'features' => [
                '20 análises de IA por mês',
                'Limite de lance visando lucro',
                '6 recortes de alerta (um por modelo)',
                'Aviso 1 hora antes nos carros com interesse',
            ],
        ],
        'radar_pro' => [
            'name' => 'Radar Pro',
            'tagline' => 'Quem vive de leilão usa IA em todo lote sério.',
            'price' => 'R$ 97/mês',
            'price_note' => 'Prioridade na fila de aprovação.',
            'analyses_per_month' => 80,
            'alerts' => 12,
            'highlight' => true,
            'cta' => 'Quero o Pro',
            'features' => [
                '80 análises de IA por mês',
                'Parecer com fotos, risco e checklist de pátio',
                '12 recortes de alerta',
                'Digest + lembrete de leilão + suporte direto',
            ],
        ],
    ],
];
